name = "IntervalMonoFuncs"
uuid = "4c44cab3-685a-4d4f-a3f2-2eeea13c7f9a"
authors = ["Roy Wang <rwang013@uottawa.ca> and contributors"]
version = "0.1.0"

[deps]
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
NLopt = "0.6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
